### PR TITLE
fix: Resolves #1052 - Not a valid Bluetooth Address

### LINKED ISSUE #1052: Not a valid Bluetooth Address
Hi Team,

When we include a random address to the manager.isDeviceConnected(address), the library is throwing a Native error. Can we get a try catch handler implemented in the native side?
Thank you for the amazing library.

IMG_1591

### PR DESCRIPTION
**Pull request by gmiszewski-intent**
This was fixed already, but error was suppressed in native.
Now it's logged in logcat.

### CODE REVIEW

File: example/src/services/BLEService/BLEService.ts [hunk 1]
```diff
@@ -280,11 +280,11 @@ class BLEServiceInstance {
       this.showErrorToast(deviceNotConnectedErrorText)
       throw new Error(deviceNotConnectedErrorText)
     }
-    return this.manager.isDeviceConnected(this.device.id).catch(error => {
-      this.onError(error)
-    })
+    return this.manager.isDeviceConnected(this.device.id)
   }
 
+  isDeviceWithIdConnected = (id: string) => this.manager.isDeviceConnected(id).catch(console.error)
```
Comment (eliaslecomte) [inline example/src/services/BLEService/BLEService.ts:286]: It's good practice to infer the type, via `Device['id']`

Comment (dominik-czupryna-withintent) [reply example/src/services/BLEService/BLEService.ts:286]: already fixed in https://github.com/dotintent/react-native-ble-plx/pull/1111

**Review by dominik-czupryna-withintent — DISMISSED** [review]

**Review by dominik-czupryna-withintent — APPROVED** [review]

**Review by dominik-czupryna-withintent — APPROVED** [review]
