### PR TITLE
fix: resolves #1103 - crash on disconnect

### LINKED ISSUE #1103: 🐛 Android crashes on bluetooth device disconnect
### Prerequisites

- [X] I checked the documentation and FAQ without finding a solution
- [X] I checked to make sure that this issue has not already been filed

### Expected Behavior

shouldnt crash

### Current Behavior

crashes

### Library version

3.0.0

### Device

pixle 7a

### Environment info

```shell
see screenshot
```

### Steps to reproduce

1. connect to device
2. disconnect(i just shut down the power on the Bluetooth device)
3. crashes
env info:
Screenshot 2023-10-03 at 11 23 52 AM

crash:
Screenshot 2023-10-03 at 11 24 23 AM

### Formatted code sample or link to a repository

```js
sorry let me know if you really need that but I think the stack trace should be good nuff right?
```

### Relevant log output

```shell
see screenshots
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by gmiszewski-intent**
The issue origin starts in RxAndroidBle library - for now I only added global handling of undeliverable RxJava errors, with message in logcat.

### CODE REVIEW

File: example/src/components/atoms/TestStateDisplay/TestStateDisplay.tsx [hunk 1]
```diff
@@ -21,7 +21,7 @@ export function TestStateDisplay({ label, state, value }: TestStateDisplayProps)
     <Container>
       <Header>
         <Label>{label}</Label>
-        <AppText>{marks[state]}</AppText>
+        {state && <AppText>{marks[state]}</AppText>}
```
Comment (eliaslecomte) [inline example/src/components/atoms/TestStateDisplay/TestStateDisplay.tsx:24]: It's better to use a terniary in views, so:
```
{state ? <AppText>{marks[state]}</AppText> : null}
```

If a boolean false would be passed to `state` it would now visualize `False`.

File: example/src/services/BLEService/BLEService.ts [hunk 2]
```diff
@@ -77,6 +77,16 @@ class BLEServiceInstance {
       })
   }
 
+  disconnectDeviceById = (id: string) =>
```
Comment (eliaslecomte) [inline example/src/services/BLEService/BLEService.ts:80]: It's possible to type this is `DeviceId` or even better as `Device['id']`.

File: example/src/components/atoms/TestStateDisplay/TestStateDisplay.tsx (hunk 1 above)
Comment (dominik-czupryna-withintent) [reply example/src/components/atoms/TestStateDisplay/TestStateDisplay.tsx:24]: Are you sure? As far as I know, visualizing False was removed a few years ago. When conditional rendering gets false it just not rendering (renders nothing in this place). The problem will only appear when you use the number 0 as a condition. The component allows you to pass only 'DONE' | 'WAITING' | 'ERROR' | 'IN_PROGRESS' values in this place. As a result, in this case, adding `: null` does not help at all, but prolongs the code. To be fully safe, all we need to do is parse the condition to boolean. 
eg.
Screenshot 2023-10-11 at 11 02 17

File: example/src/services/BLEService/BLEService.ts (hunk 2 above)
Comment (dominik-czupryna-withintent) [reply example/src/services/BLEService/BLEService.ts]: Done

**Comment by gmiszewski-intent** [comment]
I added one more small fix for Android.
Because of native library that we use, we need to handle situation where user runs connect method multiple times. 

There was a bug when user tried to run connectWithDevice method multiple times.

**Review by dominik-czupryna-withintent — APPROVED** [review]

**Review by intent-kacper-cyranowski — APPROVED** [review]
